services:
  craig:
    build: .
    # Or use: image: docker.io/vroles/craig:latest
    container_name: craig
    ports:
      - "3222:3222"  # Dashboard
      - "5029:5029"  # API
    volumes:
      - craig_rec:/app/rec
      - ./install.config:/app/install.config:ro
    networks:
      - craig-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - PORT=3222
    # Remove depends_on if using external Redis/Postgres
    # depends_on:
    #   redis:
    #     condition: service_started
    restart: unless-stopped

volumes:
  craig_rec:
    driver: local

networks:
  craig-network:
    driver: bridge
    # If Postgres/Redis are on a different network, use external:
    # external: true
    # name: your-existing-network-name